categories = {
	{name = "Foundations", id = 1, c = true},
	{name = "Panels", id = 2, c = true},
	{name = "Sport ", id = 3, c = false},
	{name = "Racing", id = 4, c = true},
	{name = "Guns", id = 5, c = false},
	{name = "Brands", id=7, c = true},
	{name = "Bbjects", id = 8, c = true},
	{name = "Vehicles", id = 9, c = false},
	{name = "Vegetation", id = 10, c = true},
	{name = "Barrier", id = 11, c = false},
	{name = "Flags", id = 12, c = true},
	{name = "StreetLights", id = 13, c = true},
	{name = "Decoration", id = 14, c = true},
	{name = "Other", id = 15, c = true}
}


sous_categories= {
	{name = "Interior fittings", parent_id = 1, child_id = 1},
	{name = "Exterior completions", parent_id = 1, child_id = 2},
	{name = "Doors/Windows", parent_id = 1, child_id = 3},
	{name = "Foundations", parent_id = 1, child_id = 5},
	{name = "Ads", parent_id = 7, child_id = 6},
	{name = "Beach Part 1", parent_id = 15, child_id = 32},
	{name = "Beach Part 2", parent_id = 15, child_id = 33},
	{name = "Bikini/beers 1", parent_id = 15, child_id = 34},
	{name = "billboards 1", parent_id = 15, child_id = 35},
	{name = "billboards 2", parent_id = 15, child_id = 36},
	{name = "Bin 1", parent_id = 15, child_id = 37},
	{name = "Other part 1", parent_id = 15, child_id = 38},
	{name = "Other part 2", parent_id = 15, child_id = 39},
	{name = "Part 1", parent_id = 4, child_id = 40},
	{name = "Part 2", parent_id = 4, child_id = 41},
	{name = "Part 3", parent_id = 4, child_id = 42},
	{name = "Part 4", parent_id = 4, child_id = 43},
	{name = "Part 5", parent_id = 4, child_id = 44},
	{name = "Part 6", parent_id = 4, child_id = 45},
	{name = "Part 7", parent_id = 4, child_id = 46},
	{name = "Part 8", parent_id = 4, child_id = 47},
	{name = "Tyre wall Part 1", parent_id = 4, child_id = 48},
	{name = "Tyre wall Part 2", parent_id = 4, child_id = 49},
	{name = "Wallride Part 1", parent_id = 4, child_id = 50},
	{name = "Folliage", parent_id = 10, child_id = 7},
	{name = "Tree", parent_id = 10, child_id = 8},
	{name = "Tree (Part. 2)", parent_id = 10, child_id = 30},
	{name = "Tree (Part. 3)", parent_id = 10, child_id = 31},
	{name = "Plants", parent_id = 10, child_id = 9},
	{name = "Plants (Part. 2)", parent_id = 10, child_id = 20},
	{name = "Planters", parent_id = 10, child_id = 10},
	{name = "Part 1", parent_id = 14, child_id = 11},
	{name = "Part 2", parent_id = 14, child_id = 12},
	{name = "Part 3", parent_id = 14, child_id = 13},
	{name = "Part 4", parent_id = 14, child_id = 14},
	{name = "Part 5", parent_id = 14, child_id = 15},
	{name = "Part 6", parent_id = 14, child_id = 16},
	{name = "Part 7", parent_id = 14, child_id = 17},
	{name = "Part 8", parent_id = 14, child_id = 18},
	{name = "Part 9", parent_id = 14, child_id = 19},
	{name = "Part 1", parent_id = 13, child_id = 21},
	{name = "Part 2", parent_id = 13, child_id = 22},
	{name = "Part 1", parent_id = 12, child_id = 23},
	{name = "Part 2", parent_id = 12, child_id = 24},
	{name = "Part 1", parent_id = 8, child_id = 25},
	{name = "Part 2", parent_id = 8, child_id = 26},
	{name = "Part 3", parent_id = 8, child_id = 29},
	{name = "Part 1", parent_id = 2, child_id = 27},
	{name = "Part 2", parent_id = 2, child_id = 28},

}


---- 13 12 8 2

categories_id = {}


categories_id[2] = {

}


categories_id[3] = {
	"stt_prop_stunt_bowling_ball",
	"stt_prop_stunt_bowling_pin",
	"stt_prop_stunt_soccer_ball",
	"stt_prop_stunt_soccer_lball",
	"prop_bar_pump_01",
	"prop_bar_pump_10",
	"prop_bar_pump_09",
	"prop_bar_pump_08",
	"prop_bar_pump_07",
	"prop_bar_pump_06",
	"prop_bar_pump_05",
	"prop_bar_pump_04",
	"prop_basejump_target_01",
	"prop_beachflag_le",
	"prop_bbq_2",
	"prop_bbq_3",
	"stt_prop_stunt_soccer_sball"
}






categories_id[5] = {
	"hei_prop_carrier_defense_01",
	"stt_prop_c4_stack",
	"stt_prop_stunt_tube_fn_02",
	"stt_prop_stunt_tube_fn_03",
	"stt_prop_stunt_tube_fn_04",
	"stt_prop_stunt_tube_fn_05",
	"stt_prop_stunt_tube_jmp2",
	"hei_prop_hei_ammo_pile",
	"hei_prop_hei_ammo_pile_02",
	"hei_prop_hei_ammo_single",
}


categories_id[8] = {

}

categories_id[9] = {
	"hei_prop_heist_tug",
	"prop_byard_dingy",
	"prop_byard_rowboat1",
	"prop_byard_rowboat3",
	"prop_byard_rowboat4",
	"prop_can_canoe",
	"prop_crashed_heli",
}


categories_id[11] = {
	"prop_premier_fence_01",
	"prop_ch2_wdfence_01",
	"prop_ch2_wdfence_02",
	"prop_premier_fence_02",
	"prop_gold_vault_fence_l",
	"prop_gold_vault_fence_r",
	"prop_ld_barrier_01",
	"prop_barrier_work05",
	"prop_barrier_work04a",
	"prop_barrier_work06a",
	"p_barriercrash_01_s",
	"prop_byard_bench01",
	"prop_byard_bench02",
	"prop_const_fence01b_cr",
	"prop_const_fence02a",
	"prop_const_fence02b",
	"prop_const_fence03a_cr",
	"prop_const_fence03b_cr",
}


categories_id[12] = {
	
}





categories_id[13] = {
}




sub_categorie = {}

sub_categorie[1] = {
	"des_scaffolding_root",
	"des_server_root",
}

sub_categorie[2] = {
	"des_frenchdoors_start",
	"prop_bollard_02a",
	"prop_bollard_02b",
	"prop_bollard_02c",
	"prop_bollard_04",
	"prop_bollard_05",
	"des_scaffolding_tank_root",
	"prop_air_sechut_01",
	"prop_helipad_01",
	"prop_helipad_02",
	"prop_rural_windmill",
	"prop_sec_barier_01a",
	"p_oil_pjack_03_s",
	"p_oil_pjack_02_s",
	"p_oil_pjack_01_s",
	"prop_windmill1",
	"prop_windmill_01",
	"lts_prop_lts_elecbox_24",
"lts_prop_lts_elecbox_24b",
"lts_prop_lts_offroad_tyres01",
"lts_prop_tumbler_01_s2",
"lts_prop_tumbler_cs2_s2",
}

sub_categorie[3] = {
	"02gate3_l",
	"des_frenchdoors_start",
	"dt1_03_mp_door",
	"dt1_20_didier_mp_door",
	"hei_dt1_03_mph_door_01",
	"hei_heist_apart2_door",
	"hei_prop_bh1_08_hdoor",
	"hei_prison_heist_clothes",
	"hei_prop_bh1_08_mp_gar2",
	"hei_prop_bh1_09_mph_r",
	"hei_prop_bh1_09_mp_gar2",
	"hei_prop_dt1_20_mph_door_r",
	"hei_prop_dt1_20_mp_gar2",
	"hei_prop_gold_trolly_empty",
	"hei_prop_heist_cutscene_doora",
	"hei_prop_heist_cutscene_doorb",
	"hei_prop_heist_cutscene_doorc_r",
	"hei_prop_yah_glass_01",
	"hei_prop_yah_glass_02",
	"hei_prop_yah_glass_03",
	"hei_prop_yah_glass_04",
	"hei_prop_yah_glass_05",
	"hei_prop_yah_glass_06",
	"hei_prop_yah_glass_07",
	"hei_prop_yah_glass_08",
	"hei_prop_yah_glass_09",
	"hei_prop_yah_glass_10",
	"hei_prop_hei_bankdoor_new",
}


sub_categorie[4] = {
	"hei_prop_zip_tie_straight",
}


sub_categorie[5] = {
	"des_cables_root",
	"des_fibstair_root",
	"des_fib_ceil2_root",
	"des_fib_ceil_rootb",
	"des_floor_root",
	--"hei_heist_flecca_weapons",
	"hei_heist_sh_bong_01",
}

sub_categorie[6] = {
	"stt_prop_tyre_wall_010",
	"stt_prop_tyre_wall_011",
	"stt_prop_tyre_wall_012",
	"stt_prop_tyre_wall_013",
	"stt_prop_tyre_wall_014",
	"stt_prop_tyre_wall_015",
	"stt_prop_tyre_wall_02",
	"stt_prop_tyre_wall_03",
	"stt_prop_tyre_wall_04",
	"stt_prop_tyre_wall_05",
	"stt_prop_tyre_wall_06",
	"stt_prop_tyre_wall_07",
	"stt_prop_tyre_wall_08",
	"stt_prop_tyre_wall_09",
	"prop_airport_sale_sign",
}



sub_categorie[7] = {
	"prop_bush_lrg_01c_cr",
	"prop_bush_lrg_01e_cr",
	"prop_bush_lrg_01e_cr2",
	"prop_bush_med_03_cr",
	"prop_bush_med_03_cr2",
	"prop_plant_group_04_cr",
	"prop_fib_plant_02",
}


sub_categorie[8] = {
	"hei_prop_hei_tree_fallen_02",
	"prop_tree_fallen_02",
	"prop_tree_eng_oak_cr2",
	"prop_tree_eng_oak_creator",
	"prop_tree_eng_oak_01",
	"prop_tree_oak_01",
	"prop_tree_olive_cr2",
	"prop_tree_olive_creator",
	"prop_xmas_tree_int",
	"prop_joshua_tree_01a",
	"prop_joshua_tree_01b",
	"prop_joshua_tree_01c",
	"prop_joshua_tree_01d",
	"prop_joshua_tree_01e",
	"prop_joshua_tree_02a",
	"prop_joshua_tree_02b",
	"prop_joshua_tree_02c",
	"prop_joshua_tree_02d",
	"prop_joshua_tree_02e",
	"prop_cactus_01a",
	"prop_cactus_01b",
	"prop_cactus_01c",
	"prop_cactus_01d",
	
}


sub_categorie[30] = {
	"prop_cactus_01e",
	"prop_cactus_02",
	"prop_sapling_break_01",
	"prop_sapling_break_02",
	"prop_tree_olive_01",
	"prop_tree_pine_01",
	"prop_tree_pine_02",
	"prop_tree_stump_01",
	"prop_tree_birch_01",
	"prop_tree_birch_02",
	"prop_tree_birch_01",
	"prop_tree_birch_02",
	"prop_tree_birch_03",
	"prop_tree_birch_03b",
	"prop_tree_birch_04",
	"prop_tree_cedar_02",
	"prop_tree_cedar_03",
	"prop_tree_cedar_04",
	"prop_tree_cedar_s_01",
	"prop_tree_cedar_s_02",
	"prop_tree_cedar_s_04",
	"prop_tree_cedar_s_05",
	"prop_tree_cedar_s_06",
}


sub_categorie[31] = {
	"prop_tree_cypress_01",
	"prop_tree_eucalip_01",
	"prop_tree_jacada_01",
	"prop_tree_jacada_02",
	"prop_tree_lficus_02",
	"prop_tree_lficus_03",
	"prop_tree_lficus_05",
	"prop_tree_lficus_06",
}
---Beach 1
sub_categorie[32] = {
	"prop_beachbag_combo_02",
	"prop_beachbag_combo_01",
	"prop_beachbag_06",
	"prop_beachbag_05",
	"prop_beachbag_04",
	"prop_beachbag_03",
	"prop_beachbag_02",
	"prop_beachbag_01",
	"prop_beachball_02",
	"prop_beach_bars_01",
	"prop_beach_lg_float",
	"prop_beach_lg_stretch",
	"prop_beach_lg_surf",
	"prop_beach_lotion_01",
	"prop_beach_lotion_02",
	"prop_beach_lotion_03",
	"prop_beach_punchbag",
	"prop_beach_rings_01",
	"prop_beach_sculp_01",
	"prop_beach_towel_02",
	"prop_beach_volball01",
}
----Beach2
sub_categorie[33] = {
	"prop_beach_volball02",
	"prop_beach_bars_02",
	"prop_beach_fire",
	"prop_beach_dip_bars_02",
	"prop_beach_dip_bars_01",
	"prop_beach_bbq",
}
------
sub_categorie[34] = {
	"prop_beerneon",
	"prop_beer_bison",
	"prop_beer_box_01",
	"prop_beer_neon_02",
	"prop_beer_neon_03",
	"prop_beer_neon_04",
	"prop_beggers_sign_04",
	"prop_beggers_sign_03",
	"prop_beggers_sign_02",
	"prop_beggers_sign_01",
	"prop_beta_tape",
	"prop_beware_dog",
	"prop_bikini_disp_02",
	"prop_bikini_disp_06",
	"prop_bikini_disp_05",
	"prop_bikini_disp_04",
	"prop_bikini_disp_03",
	"prop_bikini_disp_01",
	
	}
---- لافتات دعايات
sub_categorie[35] = {
	"prop_billboard_09wall",
	"prop_billboard_16",
	"prop_billboard_15",
	"prop_billboard_14",
	"prop_billboard_13",
	"prop_billboard_12",
	"prop_billboard_11",
	"prop_billboard_10",
	"prop_billboard_09",
	"prop_billboard_08",
	"prop_billboard_07",
	"prop_billboard_06",
	"prop_billboard_05",
	"prop_billboard_04",
	"prop_billboard_03",
	"prop_billboard_02",
	"prop_billboard_01",
	"prop_billb_frame01a",
    "prop_billb_frame01a",
    "prop_billb_frame01b",
    "prop_billb_frame02a",
    }
	
sub_categorie[36] = {
    "prop_billb_frame02b",
    "prop_billb_frame03a",
    "prop_billb_frame03b",
    "prop_billb_frame03c",
    "prop_billb_frame04a",
    "prop_billb_frame04b",

    
	}
----نفايات	
sub_categorie[37] = {
	"prop_binoc_01",
    "prop_bin_04a",
    "prop_bin_10a",
    "prop_bin_11a",
    "prop_bin_11b",
    "prop_bin_12a",
    "prop_bin_13a",
    "prop_bin_14a",
    "prop_bin_14b",
    "prop_bin_beach_01d",
    "prop_bin_delpiero",
    "prop_bin_delpiero_b",
	}
	
sub_categorie[38] = {
    "prop_biolab_g_door",
    "prop_biotech_store",
    "prop_bison_winch",
    "prop_blackjack_01",
    "prop_bleachers_05",
    "prop_bleachers_04",
    "prop_bleachers_03",
    "prop_bleachers_02",
    "prop_bleachers_01",
    "prop_blox_spray",
    "prop_bmu_01",
    "prop_bmu_01_b",
    "prop_bmu_02",
    "prop_bmu_02_ld",
    "prop_bmu_02_ld_cab",
    "prop_bmu_02_ld_sup",
    "prop_bmu_track01",
    "prop_bmu_track02",
    "prop_bmu_track03",
    "prop_boogieboard_02",
    "prop_boogieboard_01",
   
   

}

  sub_categorie[39] = {
    "prop_boogieboard_10",
    "prop_boogieboard_09",
    "prop_boogieboard_08",
    "prop_boogieboard_07",
    "prop_boogieboard_06",
    "prop_boogieboard_05",
    "prop_boogieboard_04",
    "prop_boogieboard_03",
    "lts_prop_lts_ramp_01",
    "lts_prop_lts_ramp_02",
    "lts_prop_lts_ramp_03",
}
	
 sub_categorie[40] = {
    "stt_prop_stunt_bblock_huge_01",
    "stt_prop_stunt_bblock_huge_02",
    "stt_prop_stunt_bblock_huge_05",
    "stt_prop_stunt_bblock_huge_04",
    "stt_prop_stunt_bblock_huge_03",
    "stt_prop_stunt_bblock_hump_01",
    "stt_prop_stunt_bblock_lrg1",
    "stt_prop_stunt_bblock_hump_02",
    "stt_prop_stunt_bblock_lrg2",
    "stt_prop_stunt_bblock_lrg3",
    "stt_prop_stunt_bblock_mdm1",
    "stt_prop_stunt_bblock_mdm2",
    "stt_prop_stunt_bblock_mdm3",
    "stt_prop_stunt_bblock_qp",
    "stt_prop_stunt_bblock_qp2",
    "stt_prop_stunt_bblock_qp3",
    "stt_prop_stunt_bblock_sml1",
    "stt_prop_stunt_bblock_sml2",
    "stt_prop_stunt_bblock_sml3",
    "stt_prop_stunt_bblock_xl1",
    "stt_prop_stunt_bblock_xl2",
    "stt_prop_stunt_bblock_xl3",
    
   }
   sub_categorie[41] = {
	"stt_prop_stunt_tube_fn_01",
	"stt_prop_stunt_tube_fn_02",
	"stt_prop_stunt_tube_fn_03",
	"stt_prop_stunt_tube_fn_04",
	"stt_prop_stunt_tube_fn_05",
	"stt_prop_stunt_tube_jmp2",
	"stt_prop_race_gantry_01",
	"stt_prop_hoop_constraction_01a",
	"stt_prop_race_start_line_01",
	"stt_prop_race_start_line_01b",
	"stt_prop_race_start_line_02",
	"stt_prop_race_start_line_02b",
	"stt_prop_race_start_line_03",
	"stt_prop_race_start_line_03b",
	"stt_prop_race_tannoy",
	"stt_prop_ramp_adj_flip_m",
	"stt_prop_ramp_adj_flip_mb",
	"stt_prop_ramp_adj_flip_s",
	"stt_prop_ramp_adj_flip_sb",
	"stt_prop_ramp_adj_hloop",
	"stt_prop_ramp_adj_loop",
	"stt_prop_ramp_jump_l",
}
   sub_categorie[42] = {
	"stt_prop_stunt_bowlpin",
	"stt_prop_stunt_domino",
	"stt_prop_stunt_jump15",
	"stt_prop_stunt_jump30",
	"stt_prop_stunt_jump45",
	"stt_prop_stunt_jump_l",
	"stt_prop_stunt_jump_lb",
	"stt_prop_stunt_jump_loop",
	"stt_prop_stunt_jump_m",
	"stt_prop_stunt_jump_mb",
	"stt_prop_stunt_jump_s",
	"stt_prop_stunt_jump_sb",
	"stt_prop_stunt_landing_zone_01",
	"stt_prop_stunt_ramp",
	"stt_prop_stunt_soccer_goal",
	"stt_prop_stunt_target",
	"stt_prop_stunt_target_small",
	"stt_prop_stunt_track_bumps",
	"stt_prop_stunt_track_cutout",
	"stt_prop_stunt_track_dwlink",
	"stt_prop_stunt_track_dwlink_02",
	"stt_prop_stunt_track_dwsh15",
	
	}
	 sub_categorie[43] = {
	 
	 "stt_prop_stunt_track_dwshort",
	 "stt_prop_stunt_track_dwslope15",
	 "stt_prop_stunt_track_dwslope30",
	 "stt_prop_stunt_track_dwslope45",
	 "stt_prop_stunt_track_dwturn",
	 "stt_prop_stunt_track_exshort",
	 "stt_prop_stunt_track_fork",
	 "stt_prop_stunt_track_funlng",
	 "stt_prop_stunt_track_funnel",
	 "stt_prop_stunt_track_hill",
	 "stt_prop_stunt_track_jump",
	 "stt_prop_stunt_track_hill2",
	 "stt_prop_stunt_track_link",
	 "stt_prop_stunt_track_otake",
	 "stt_prop_stunt_track_sh15",
	 "stt_prop_stunt_track_sh30",
	 "stt_prop_stunt_track_sh45",
	 "stt_prop_stunt_track_sh45_a",
	 "stt_prop_stunt_track_short",
	 "stt_prop_stunt_track_slope15",
	 "stt_prop_stunt_track_slope30",
	 "stt_prop_stunt_track_slope45",
	 "stt_prop_stunt_track_start",
	
	}
	sub_categorie[44] = {
	 "stt_prop_stunt_track_start_02",
	 "stt_prop_stunt_track_straight",
	 "stt_prop_stunt_track_straightice",
	 "stt_prop_stunt_track_st_01",
	 "stt_prop_stunt_track_st_02",
	 "stt_prop_stunt_track_turn",
	 "stt_prop_stunt_track_turnice",
	 "stt_prop_stunt_track_uturn",
	 "stt_prop_stunt_tube_crn2",
	 "stt_prop_stunt_tube_crn",
	 "stt_prop_stunt_tube_crn_15d",
	 "stt_prop_stunt_tube_crn_30d",
	 "stt_prop_stunt_tube_crn_5d",
	 "stt_prop_stunt_tube_cross",
	 "stt_prop_stunt_tube_end",
	 "stt_prop_stunt_tube_ent",
	 "stt_prop_stunt_tube_fork",
	 "stt_prop_stunt_tube_gap_01",
	 "stt_prop_stunt_tube_gap_02",
	 "stt_prop_stunt_tube_gap_03",
	 "stt_prop_stunt_tube_hg",
	 "stt_prop_stunt_tube_jmp",
	 "stt_prop_stunt_tube_l",
	
	
	}
	sub_categorie[45] = {
	 "stt_prop_stunt_tube_m",
	 "stt_prop_stunt_tube_qg",
	 "stt_prop_stunt_tube_s",
	 "stt_prop_stunt_tube_speed",
	 "stt_prop_stunt_tube_speeda",
	 "stt_prop_stunt_tube_speedb",
	 "stt_prop_stunt_tube_xs",
	 "stt_prop_stunt_tube_xxs",
	 "stt_prop_stunt_wideramp",
	 "stt_prop_track_bend2_bar_l",
	 "stt_prop_track_bend2_bar_l_b",
	 "stt_prop_track_bend2_l",
	 "stt_prop_track_bend2_l_b",
	 "stt_prop_track_bend_15d",
	 "stt_prop_track_bend_15d_bar",
	 "stt_prop_track_bend_180d",
	 "stt_prop_track_bend_180d_bar",
	 "stt_prop_track_bend_30d",
	 "stt_prop_track_bend_30d_bar",
	 "stt_prop_track_bend_5d",
	 "stt_prop_track_bend_5d_bar",
	 "stt_prop_track_bend_bar_l",
	 "stt_prop_track_bend_bar_l_b",
	
	
	}
	sub_categorie[46] = {
	 "stt_prop_track_bend_bar_m",
	 "stt_prop_track_bend_l",
	 "stt_prop_track_bend_l_b",
	 "stt_prop_track_bend_m",
	 "stt_prop_track_block_01",
	 "stt_prop_track_block_02",
	 "stt_prop_track_block_03",
	 "stt_prop_track_chicane_l",
	 "stt_prop_track_chicane_l_02",
	 "stt_prop_track_chicane_r",
	 "stt_prop_track_chicane_r_02",
	 "stt_prop_track_cross",
	 "stt_prop_track_cross_bar",
	 "stt_prop_track_fork",
	 "stt_prop_track_fork_bar",
	 "stt_prop_track_funnel",
	 "stt_prop_track_funnel_ads_01a",
	 "stt_prop_track_funnel_ads_01b",
	 "stt_prop_track_funnel_ads_01c",
	 "stt_prop_track_jump_01a",
	 "stt_prop_track_jump_01b",
	 "stt_prop_track_jump_01c",
	 "stt_prop_track_jump_02a",
	
	
	}
		sub_categorie[47] = {
	 "stt_prop_track_jump_02b",
"stt_prop_track_jump_02c",
"stt_prop_track_link",
"stt_prop_track_slowdown",
"stt_prop_track_slowdown_t1",
"stt_prop_track_slowdown_t2",
"stt_prop_track_speedup",
"stt_prop_track_speedup_t1",
"stt_prop_track_speedup_t2",
"stt_prop_track_start",
"stt_prop_track_start_02",
"stt_prop_track_straight_bar_l",
"stt_prop_track_straight_bar_m",
"stt_prop_track_straight_bar_s",
"stt_prop_track_straight_l",
"stt_prop_track_straight_lm",
"stt_prop_track_straight_lm_bar",
"stt_prop_track_straight_m",
"stt_prop_track_straight_s",
"stt_prop_track_tube_01",
"stt_prop_tyre_wall_01",
"stt_prop_tyre_wall_010",
	
	
	}
	sub_categorie[48] = {
	"stt_prop_tyre_wall_011",
"stt_prop_tyre_wall_012",
"stt_prop_tyre_wall_013",
"stt_prop_tyre_wall_014",
"stt_prop_tyre_wall_015",
"stt_prop_tyre_wall_02",
"stt_prop_tyre_wall_03",
"stt_prop_tyre_wall_04",
"stt_prop_tyre_wall_05",
"stt_prop_tyre_wall_06",
"stt_prop_tyre_wall_07",
"stt_prop_tyre_wall_08",
"stt_prop_tyre_wall_09",
"stt_prop_tyre_wall_0l010",
"stt_prop_tyre_wall_0l012",
"stt_prop_tyre_wall_0l013",
"stt_prop_tyre_wall_0l014",
"stt_prop_tyre_wall_0l015",
"stt_prop_tyre_wall_0l018",
"stt_prop_tyre_wall_0l019",
"stt_prop_tyre_wall_0l020",
"stt_prop_tyre_wall_0l04",
"stt_prop_tyre_wall_0l05",
	}
	
	sub_categorie[49] = {
	"stt_prop_tyre_wall_0l06",
"stt_prop_tyre_wall_0l07",
"stt_prop_tyre_wall_0l08",
"stt_prop_tyre_wall_0l1",
"stt_prop_tyre_wall_0l16",
"stt_prop_tyre_wall_0l2",
"stt_prop_tyre_wall_0l3",
"stt_prop_tyre_wall_0r010",
"stt_prop_tyre_wall_0r011",
"stt_prop_tyre_wall_0r012",
"stt_prop_tyre_wall_0r013",
"stt_prop_tyre_wall_0r014",
"stt_prop_tyre_wall_0r015",
"stt_prop_tyre_wall_0r016",
"stt_prop_tyre_wall_0r017",
"stt_prop_tyre_wall_0r018",
"stt_prop_tyre_wall_0r019",
"stt_prop_tyre_wall_0r04",
"stt_prop_tyre_wall_0r05",
"stt_prop_tyre_wall_0r06",
"stt_prop_tyre_wall_0r07",
"stt_prop_tyre_wall_0r08",
"stt_prop_tyre_wall_0r09",
	}
	sub_categorie[50] = {
	
	"stt_prop_wallride_01",
	"stt_prop_wallride_01b",
"stt_prop_wallride_02",
"stt_prop_wallride_02b",
"stt_prop_wallride_04",
"stt_prop_wallride_05",
"stt_prop_wallride_05b",
"stt_prop_wallride_45l",
"stt_prop_wallride_45la",
"stt_prop_wallride_45r",
"stt_prop_wallride_45ra",
"stt_prop_wallride_90l",
"stt_prop_wallride_90lb",
"stt_prop_wallride_90r",
"stt_prop_wallride_90rb",
	}
sub_categorie[9] = {
	"prop_fbibombplant",
	"prop_plant_int_02a",
	"prop_plant_int_02b",
	"p_int_jewel_plant_01",
	"p_int_jewel_plant_02",
	"prop_fib_plant_01",
	"prop_plant_int_04a",
	"prop_plant_int_04b",
	"prop_plant_int_04c",
	"prop_plant_palm_01a",
	"prop_plant_palm_01b",
	"prop_plant_palm_01c",
	"prop_pot_plant_01a",
}


sub_categorie[20] = {
	"prop_pot_plant_01b",
	"prop_pot_plant_01c",
	"prop_pot_plant_01d",
	"prop_pot_plant_01e",
	"prop_pot_plant_03b",
	"prop_pot_plant_03b_cr2",
	"prop_pot_plant_03c",
	"prop_pot_plant_04b",
	"prop_pot_plant_04c",
	"prop_pot_plant_05a",
	"prop_pot_plant_05b",
	"prop_pot_plant_05c",
	"prop_pot_plant_05d",
}


sub_categorie[10] = {
	"prop_ld_dstplanter_01",
	"prop_ld_dstplanter_02",
	"prop_ld_planter1a",
	"prop_ld_planter1b",
	"prop_ld_planter1c",
	"prop_ld_planter2a",
	"prop_ld_planter2b",
	"prop_ld_planter2c",
	"prop_ld_planter3a",
	"prop_ld_planter3b",
	"prop_ld_planter3c",
	"prop_windowbox_a",
	"prop_windowbox_b",
	"prop_windowbox_broken",
	"prop_windowbox_small",
}

sub_categorie[11] = {
	"prop_ld_faucet",
	"prop_ld_int_safe_01",
	"prop_mp_cone_01",
	"prop_mp_cone_02",
	"prop_mp_cone_03",
	"prop_mp_cone_04",
	"prop_phonebox_05a",
	"prop_plas_barier_01a",
	"prop_premier_fence_01",
	"prop_premier_fence_02",
	"prop_proxy_chateau_table",
	"prop_ql_revolving_door",
	"prop_quad_grid_line",
	"prop_rail_points01",
	"prop_rail_points02",
	"prop_rf_conc_pillar",
	"prop_roadcone01a",
	"prop_roadcone01b",
	"prop_roadcone01c",
	"prop_roadcone02a",
	"prop_roadcone02b",
	"prop_roadcone02c",
	"prop_rock_chair_01",
}

sub_categorie[12] = {
	"prop_rub_couch01",
	"prop_rub_scrap_02",
	"prop_rub_scrap_03",
	"prop_rub_scrap_04",
	"prop_rub_scrap_05",
	"prop_rub_scrap_06",
	"prop_rub_scrap_07",
	"prop_sc1_06_gate_l",
	"prop_sc1_06_gate_r",
	"prop_sc1_21_g_door_01",
	"prop_shop_front_door_l",
	"prop_shop_front_door_r",
	"prop_shuttering01",
	"prop_shuttering02",
	"prop_shuttering03",
	"prop_shuttering04",
	"prop_single_grid_line",
	"prop_skate_flatramp_cr",
	"prop_skate_funbox_cr",
	"prop_skate_halfpipe_cr",
	"prop_skate_kickers_cr",
	"prop_skate_quartpipe_cr",
	"prop_skate_spiner_cr",
}

sub_categorie[13] = {
	"prop_sluicegatel",
	"prop_sluicegater",
	"prop_sluicegate",
	"prop_start_finish_line_01",
	"prop_sub_gantry",
	"prop_sub_trans_01a",
	"prop_sub_trans_02a",
	"prop_sub_trans_04a",
	"prop_telescope",
	"prop_telescope_01",
	"prop_water_corpse_01",
	"prop_water_corpse_02",
	"prop_water_ramp_01",
	"prop_water_ramp_02",
	"prop_water_ramp_03",
	"prop_weed_01",
	"prop_weed_02",
	"prop_worklight_04a",
	"prop_yacht_seat_01",
	"prop_yacht_seat_02",
	"prop_yacht_seat_03",
	"prop_yacht_table_01",
	"prop_yacht_table_02",
}

sub_categorie[14] = {
	"p_barier_test_s",
	"p_cs_15m_rope_s",
	"p_cs_leaf_s",
	"p_cs_rope_tie_01_s",
	"p_ld_conc_cyl_01",
	"p_ld_stinger_s",
	"p_stinger_02",
	"p_stinger_03",
	"p_stinger_04",
	"p_stinger_piece_01",
	"p_stinger_piece_02",
	"rock_4_cl_2_1",
	"rock_4_cl_2_2",
	"prop_ld_toilet_01",
	"prop_ld_vault_door",
	"prop_lifeblurb_01",
	"prop_lifeblurb_01b",
	"prop_lifeblurb_02",
	"prop_lifeblurb_02b",
	"prop_life_ring_02",
	"prop_lift_overlay_01",
	"prop_lift_overlay_02",
	"prop_mp_base_marker",
	
}

sub_categorie[15] = {
	"prop_mp_max_out_lrg",
	"prop_mp_max_out_med",
	"prop_mp_max_out_sm",
	"prop_mp_placement",
	"prop_mp_placement_lrg",
	"prop_mp_placement_maxd",
	"prop_mp_placement_med",
	"prop_mp_placement_red",
	"prop_mp_placement_sm",
	"prop_offroad_barrel01",
	"prop_off_chair_01",
	"prop_off_chair_03",
	"prop_off_chair_04",
	"prop_off_chair_04b",
	"prop_off_chair_04_s",
	"prop_off_chair_05",
	"prop_oiltub_01",
	"prop_oiltub_02",
	"prop_oiltub_03",
	"prop_oiltub_05",
	"prop_oiltub_06",
	"prop_old_churn_01",
	"prop_mp_pointer_ring",
}

sub_categorie[16] = {
	"prop_old_churn_02",
	"prop_old_deck_chair",
	"prop_old_deck_chair_02",
	"prop_old_wood_chair",
	"prop_patio_heater_01",
	"prop_patio_lounger1",
	"prop_patio_lounger1b",
	"prop_patio_lounger1_table",
	"prop_patio_lounger_2",
	"prop_patio_lounger_3",
	"prop_pharm_sign_01",
	"prop_plate_stand_01",
	"prop_postcard_rack",
	"prop_pris_bench_01",
	"prop_protest_sign_01",
	"prop_protest_table_01",
	"prop_rad_waste_barrel_01",
	"prop_rail_controller",
	"prop_recyclebin_02a",
	"prop_recyclebin_02b",
	"prop_recyclebin_02_c",
	"prop_recyclebin_02_d",
	"prop_recyclebin_03_a"
}

sub_categorie[17] = {
	"prop_rock_4_c",
	"prop_rock_4_d",
	"prop_rub_binbag_sd_01",
	"prop_rub_binbag_sd_02",
	"prop_rub_cabinet01",
	"prop_rub_cabinet02",
	"prop_rub_cabinet03",
	"prop_rub_cage01a",
	"prop_rub_trolley01a",
	"prop_rub_trolley02a",
	"prop_rub_trolley03a",
	"prop_satdish_2_a",
	"prop_satdish_2_f",
	"prop_satdish_2_g",
	"prop_satdish_3_b",
	"prop_satdish_3_c",
	"prop_skid_chair_01",
	"prop_skid_chair_02",
	"prop_skid_chair_03",
	"prop_snow_flower_01",
	"prop_snow_flower_02",
	"prop_sports_clock_01",
	"prop_spot_01",
}


sub_categorie[18] = {
	"prop_speaker_01",
	"prop_speaker_02",
	"prop_speaker_03",
	"prop_speaker_05",
	"prop_speaker_06",
	"prop_speaker_07",
	"prop_speaker_08",
	"prop_strip_pole_01",
	"prop_studio_light_02",
	"prop_studio_light_03",
	"prop_test_boulder_01",
	"prop_test_boulder_02",
	"prop_test_boulder_03",
	"prop_test_boulder_04",
	"prop_till_01_dam",
	"prop_till_02",
	"prop_till_03",
	"prop_time_capsule_01",
	"prop_tool_sawhorse",
	"prop_train_ticket_02",
	"prop_train_ticket_02_tu",
	"prop_t_telescope_01b",
	"prop_umpire_01",
}


sub_categorie[19] = {
	"p_cs_paper_disp_02",
	"p_cs_paper_disp_1",
	"p_ice_box_01_s",
	"p_ice_box_proxy_col",
	"p_ld_frisbee_01",
	"p_new_j_counter_01",
	"p_new_j_counter_02",
	"p_new_j_counter_03",
	"p_patio_lounger1_s",
	"p_phonebox_02_s",
	"p_rail_controller_s",
	"v_ilev_cd_lampal_off",
	"prop_v_cam_01",
	"prop_windmill2",
	"p_cs_locker_01",
	"p_cs_locker_01_s",
	"prop_recyclebin_04_a",
	"prop_recyclebin_04_b",
	"prop_recyclebin_05_a",
	"prop_riot_shield",
	"prop_sol_chair",
}


sub_categorie[20] = {
	"prop_muscle_bench_03",
	"prop_muster_wboard_01",
	"prop_muster_wboard_02",
	"prop_news_disp_02a_s",
	"prop_mp_boost_01",
	"prop_mp_cant_place_lrg",
	"prop_mp_cant_place_med",
	"prop_mp_cant_place_sm",
	"prop_test_elevator",
	"prop_test_elevator_dl",
	"prop_test_elevator_dr",
	"prop_triple_grid_line",
	"prop_rub_planks_01",
	"prop_rub_planks_02",
	"prop_rub_planks_03",
	"prop_rub_planks_04",
	"prop_offroad_bale01",
	"prop_parking_sign_1",
	"prop_parking_sign_2",
	"prop_parking_wand_01",
}



sub_categorie[21] = {
	"prop_snow_streetlight_09",
	"prop_streetlight_01",
	"prop_streetlight_01b",
	"prop_streetlight_02",
	"prop_streetlight_03",
	"prop_streetlight_03b",
	"prop_streetlight_03c",
	"prop_streetlight_03d",
	"prop_streetlight_03e",
	"prop_streetlight_04",
	"prop_streetlight_05",
	"prop_streetlight_05_b",
	"prop_streetlight_06",
}

sub_categorie[22] = {
	"prop_streetlight_07a",
	"prop_streetlight_07b",
	"prop_streetlight_08",
	"prop_streetlight_09",
	"prop_streetlight_10",
	"prop_streetlight_11a",
	"prop_streetlight_11b",
	"prop_streetlight_11c",
	"prop_streetlight_12a",
	"prop_streetlight_12b",
	"prop_streetlight_14a",
	"prop_streetlight_15a",
	"prop_streetlight_16a",
}


sub_categorie[23] = {
	"ind_prop_dlc_flag_02",
	"ind_prop_dlc_flag_01",
	"prop_flagpole_2b",
	"prop_flagpole_2c",
	"prop_flag_canada",
	"prop_flag_canada_s",
	"prop_flag_eu",
	"prop_flag_eu_s",
	"prop_flag_france",
	"prop_flag_france_s",
	"prop_flag_german",
	"prop_flag_german_s",
	"prop_flag_ireland",
	"prop_flag_ireland_s",
	"prop_flag_japan",
	"prop_flag_japan_s",
	"prop_flag_ls",
	"prop_flag_lsfd",
	"prop_flag_lsfd_s",
	"prop_flag_lsservices",
	"prop_flag_lsservices_s",
}


sub_categorie[24] = {
	"prop_flag_ls_s",
	"prop_flag_mexico",
	"prop_flag_mexico_s",
	"prop_flag_russia",
	"prop_flag_russia_s",
	"prop_flag_s",
	"prop_flag_sa",
	"prop_flag_sapd",
	"prop_flag_sapd_s",
	"prop_flag_sa_s",
	"prop_flag_scotland",
	"prop_flag_scotland_s",
	"prop_flag_sheriff",
	"prop_flag_sheriff_s",
	"prop_flag_uk",
	"prop_flag_uk_s",
	"prop_golfflag",
	"prop_flag_us",
	"prop_flag_usboat",
	"prop_flag_us_r",
	"prop_flag_us_s"
}

sub_categorie[25] = {
	"bike_test",
	"bot_01b_bit_01",
	"bot_01b_bit_02",
	"bot_01b_bit_03",
	"cs_remote_01",
	"hei_bio_heist_gear",
	"hei_prop_bh1_09_mph_l",
	"hei_prop_cash_crate_empty",
	"hei_prop_cash_crate_half_full",
	"hei_prop_heist_box",
	"hei_prop_dt1_20_mph_door_l",
	"hei_prop_gold_trolly_half_full",
	"prop_fncwood_08b",
	"prop_fncwood_08c",
	"prop_fncwood_08d",
	"prop_fncwood_09b",
	"prop_fncwood_09c",
	"prop_fncwood_09d",
	"prop_fncwood_01a",
	"prop_fncwood_01b",
	"prop_fncwood_01c",
	"prop_fnclog_02b",
}



sub_categorie[26] = {
	"hei_prop_heist_apecrate",
	"hei_prop_heist_tub_truck",
	"hei_prop_heist_weed_block_01",
	"hei_prop_heist_weed_pallet",
	"hei_prop_heist_weed_pallet_02",
	"prop_bench_05",
	"prop_bench_09",
	"prop_big_cin_screen",
	"prop_bleachers_04_cr",
	"prop_bleachers_05_cr",
	"prop_cs_rope_tie_01",
	"stt_prop_speakerstack_01a",
	"prop_fncres_01b",
	"prop_fncres_01c",
	"prop_fncres_03a",
	"prop_fncres_03b",
	"prop_fncres_03c",
	"prop_fnclog_03a",
	"prop_haybale_03",
	"prop_ld_balastrude",
	"prop_offroad_bale02",
	"prop_offroad_bale03",
	"prop_parking_hut_2",
}


sub_categorie[29] = {
	"prop_plough",
	"prop_rebar_pile02",
	"prop_byard_ladder01",
}



sub_categorie[27] = {
	"stt_prop_corner_sign_01",
	"stt_prop_corner_sign_02",
	"stt_prop_corner_sign_03",
	"stt_prop_corner_sign_04",
	"stt_prop_corner_sign_05",
	"stt_prop_corner_sign_06",
	"stt_prop_corner_sign_07",
	"stt_prop_corner_sign_08",
	"stt_prop_corner_sign_09",
	"stt_prop_corner_sign_10",
	"stt_prop_corner_sign_11",
	"stt_prop_corner_sign_12",
	"stt_prop_corner_sign_13",
	"stt_prop_corner_sign_14",
	"stt_prop_sign_circuit_01",
	"stt_prop_sign_circuit_02",
}


sub_categorie[28] = {
	"stt_prop_sign_circuit_03",
	"stt_prop_sign_circuit_04",
	"stt_prop_sign_circuit_05",
	"stt_prop_sign_circuit_06",
	"stt_prop_sign_circuit_07",
	"stt_prop_sign_circuit_08",
	"stt_prop_sign_circuit_09",
	"stt_prop_sign_circuit_10",
	"stt_prop_sign_circuit_11",
	"stt_prop_sign_circuit_11b",
	"stt_prop_sign_circuit_12",
	"stt_prop_sign_circuit_13",
	"stt_prop_sign_circuit_13b",
	"stt_prop_sign_circuit_14",
	"stt_prop_sign_circuit_14b",
	"stt_prop_sign_circuit_15",
	"stt_prop_track_stop_sign",
	"stt_prop_slow_down",
}