RegisterNetEvent("SaveCommand")
AddEventHandler("SaveCommand", function(comment)
		x, y, z = table.unpack(GetEntityCoords(GetPlayerPed(-1), true))
		hdg = GetEntityHeading(GetPlayerPed(-1))
	    local PlayerName = GetPlayerName()
	    TriggerServerEvent("SaveCoords", PlayerName, x,y, z, comment, hdg)
		TriggerEvent("chatMessage", "POS", {191, 1, 1}, 'Coords saved. Player Heading: ' .. GetEntityHeading(GetPlayerPed(-1)) .. '')				
end)